package programming_quiz;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Gibby
 */
public class Quizgui extends javax.swing.JFrame {

    /**
     * Creates new form Quizgui
     */
    
        deck gamedeck = new deck();
        int round = 0;
        int playerscore =0;
    
    public Quizgui() {
        initComponents();
        gamedeck.initializedeck(); 
        gamedeck.shuffle();
          Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
          Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
          Reset.setVisible(false);
         Continue.setVisible(false);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Card1 = new javax.swing.JLabel();
        Card2 = new javax.swing.JLabel();
        Card1big = new javax.swing.JButton();
        Card2big = new javax.swing.JButton();
        Which = new javax.swing.JLabel();
        Continue = new javax.swing.JButton();
        Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setForeground(new java.awt.Color(0, 153, 0));

        Card1big.setText("Card 1");
        Card1big.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card1bigActionPerformed(evt);
            }
        });

        Card2big.setText("Card 2");
        Card2big.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card2bigActionPerformed(evt);
            }
        });

        Which.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Which.setForeground(new java.awt.Color(255, 255, 255));
        Which.setText("Which Card Is Bigger?");

        Continue.setText("Continue");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });

        Reset.setText("Reset");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(Card1big)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(Card2big)
                .addGap(76, 76, 76))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Which))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(Card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Card2)))
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Reset)
                    .addComponent(Continue))
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Which)
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Card1)
                    .addComponent(Card2))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Card1big)
                    .addComponent(Card2big))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(Continue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Reset)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Card1bigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card1bigActionPerformed
        // TODO add your handling code here:
        card one = gamedeck.getTopCard();
        card two = gamedeck.getTopCard();
        int onevalue = one.getvalue();
        int twovalue = two.getvalue();
        Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource(one.getImage())));
        Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource(two.getImage())));
        
        if(twovalue < onevalue)//Player Wins
        {
            playerscore++;
            Which.setText("Winner");
        }
        else if(twovalue > onevalue)// Player Loses
        {
         Which.setText("Loser");
        }
        
        Card2big.setVisible(false);
        Card1big.setVisible(false);
        Continue.setVisible(true);
        
        
        round++;
       
        
        
    }//GEN-LAST:event_Card1bigActionPerformed

    private void Card2bigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card2bigActionPerformed
        // TODO add your handling code here:
        card one = gamedeck.getTopCard();
        card two = gamedeck.getTopCard();
        int onevalue = one.getvalue();
        int twovalue = two.getvalue();
        Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource(one.getImage())));
        Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource(two.getImage())));
       
        
        if(onevalue < twovalue)//Player Wins
        {
            playerscore++;
            Which.setText("Winner");
        }
        else if(onevalue > twovalue)// Player Loses
        {
         Which.setText("Loser");
        }
        
        Card2big.setVisible(false);
        Card1big.setVisible(false);
        Continue.setVisible(true);
        
        
        round++;
       
        
    }//GEN-LAST:event_Card2bigActionPerformed

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
        // TODO add your handling code here:
        
        if(round == 10) // show the percentage
        {
            Which.setText(playerscore + "/" + round);
            Continue.setVisible(false);
            Reset.setVisible(true);
           
        }
        else
        {
        Continue.setVisible(false);
        Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
        Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
        
        Card1big.setVisible(true);
        Card2big.setVisible(true);
        Which.setText("Which Card Is Bigger?");
        
        }
        
        
        
        
    }//GEN-LAST:event_ContinueActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        gamedeck.initializedeck(); 
        gamedeck.shuffle();
        Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
        Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
        Card1big.setVisible(true);
        Card2big.setVisible(true);
        Which.setText("Which Card Is Bigger?");
        Reset.setVisible(false);
        round = 0;
        playerscore =0;
    }//GEN-LAST:event_ResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quizgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quizgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quizgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quizgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quizgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Card1;
    private javax.swing.JButton Card1big;
    private javax.swing.JLabel Card2;
    private javax.swing.JButton Card2big;
    private javax.swing.JButton Continue;
    private javax.swing.JButton Reset;
    private javax.swing.JLabel Which;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
