/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab2;
import java.util.*;
/**
 *
 * @author Dylan
 */
public class BMIGui extends javax.swing.JFrame {
        String feet;
        String inches;
        String pounds;
    
    
    /**
     * Creates new form BMIGui
     */
    public BMIGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JLayeredPane();
        feetbox = new javax.swing.JTextField();
        weightbox = new javax.swing.JTextField();
        inchesbox = new javax.swing.JTextField();
        bmi_button = new javax.swing.JButton();
        bmi_results = new javax.swing.JTextField();
        bmicalc_label = new javax.swing.JLabel();
        height_label = new javax.swing.JLabel();
        weight_label = new javax.swing.JLabel();
        feet_label = new javax.swing.JLabel();
        inches_label = new javax.swing.JLabel();
        pounds_label = new javax.swing.JLabel();
        bmi_label = new javax.swing.JLabel();
        bmicat_label = new javax.swing.JLabel();
        underweight_label = new javax.swing.JLabel();
        normal_label = new javax.swing.JLabel();
        overweight_label = new javax.swing.JLabel();
        obesity_label = new javax.swing.JLabel();
        lineone = new javax.swing.JSeparator();
        linetwo = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        feetbox.setToolTipText("");
        feetbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feetboxActionPerformed(evt);
            }
        });

        weightbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightboxActionPerformed(evt);
            }
        });

        inchesbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inchesboxActionPerformed(evt);
            }
        });

        bmi_button.setText("Calculate BMI");
        bmi_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmi_buttonActionPerformed(evt);
            }
        });

        bmicalc_label.setForeground(new java.awt.Color(0, 0, 0));
        bmicalc_label.setText("BMI Calculator");
        bmicalc_label.setToolTipText("");

        height_label.setForeground(new java.awt.Color(0, 0, 0));
        height_label.setText("Height");

        weight_label.setForeground(new java.awt.Color(0, 0, 0));
        weight_label.setText("Weight");

        feet_label.setForeground(new java.awt.Color(0, 0, 0));
        feet_label.setText("Feet");

        inches_label.setForeground(new java.awt.Color(0, 0, 0));
        inches_label.setText("Inches");

        pounds_label.setForeground(new java.awt.Color(0, 0, 0));
        pounds_label.setText("Pounds");

        bmi_label.setForeground(new java.awt.Color(0, 0, 0));
        bmi_label.setText("BMI");

        bmicat_label.setForeground(new java.awt.Color(0, 0, 0));
        bmicat_label.setText("BMI Categories");

        underweight_label.setForeground(new java.awt.Color(0, 0, 0));
        underweight_label.setText("Underweight = <18.5");

        normal_label.setForeground(new java.awt.Color(0, 0, 0));
        normal_label.setText("Normal Weight = 18.5-24.9");

        overweight_label.setForeground(new java.awt.Color(0, 0, 0));
        overweight_label.setText("Overweight = 25-29.9");

        obesity_label.setForeground(new java.awt.Color(0, 0, 0));
        obesity_label.setText("Obesity = >30");

        linetwo.setOrientation(javax.swing.SwingConstants.VERTICAL);

        panel.setLayer(feetbox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(weightbox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(inchesbox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(bmi_button, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(bmi_results, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(bmicalc_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(height_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(weight_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(feet_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(inches_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(pounds_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(bmi_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(bmicat_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(underweight_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(normal_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(overweight_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(obesity_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(lineone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(linetwo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(weight_label)
                            .addComponent(height_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(feet_label)
                                    .addComponent(feetbox, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inchesbox, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(inches_label)))
                            .addComponent(weightbox)
                            .addComponent(pounds_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bmi_button)
                        .addGap(45, 45, 45))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(bmicalc_label, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(bmi_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bmi_results)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(linetwo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(normal_label)
                            .addComponent(underweight_label)
                            .addComponent(overweight_label)
                            .addComponent(obesity_label)
                            .addComponent(bmicat_label))
                        .addContainerGap(69, Short.MAX_VALUE))))
            .addComponent(lineone)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(bmicalc_label))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bmicat_label)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(underweight_label)
                        .addGap(5, 5, 5)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(height_label)
                            .addComponent(feetbox)
                            .addComponent(inchesbox)
                            .addComponent(normal_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(feet_label)
                            .addComponent(inches_label)
                            .addComponent(overweight_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(obesity_label)
                        .addGap(2, 2, 2)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weight_label)
                            .addComponent(weightbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pounds_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(linetwo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(lineone, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bmi_label)
                    .addComponent(bmi_results)
                    .addComponent(bmi_button))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void feetboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feetboxActionPerformed
        // TODO add your handling code here: THIS IS FOR FEET
         
    }//GEN-LAST:event_feetboxActionPerformed

    private void inchesboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inchesboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inchesboxActionPerformed

    private void bmi_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmi_buttonActionPerformed
        // EVERYTHING SHOULD HAPPEN HERE WHEN THE BUTTON IS PRESSED!
        feet = feetbox.getText();
        inches = inchesbox.getText();
        pounds = weightbox.getText();
        String results="";
        int feetint;
        int inchesint;
        int poundsint;
        //Get the text and make sure that it is numbers
        if(feet.matches("[0-9]") == true && inches.matches("[0-9][0-9]?") == true && pounds.matches("[0-9][0-9]?[0-9]?[0-9]?") == true)
        {
            //Make a new BMI Calculator and convert string to int
            feetint=Integer.parseInt(feet);
            inchesint=Integer.parseInt(inches);
            poundsint=Integer.parseInt(pounds);
            BMICalculator newbmi = new BMICalculator(feetint, inchesint, poundsint);
            results = newbmi.calculate();
            bmi_results.setText(results);
        }
        
 
    }//GEN-LAST:event_bmi_buttonActionPerformed

    private void weightboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMIGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMIGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMIGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMIGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMIGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bmi_button;
    private javax.swing.JLabel bmi_label;
    private javax.swing.JTextField bmi_results;
    private javax.swing.JLabel bmicalc_label;
    private javax.swing.JLabel bmicat_label;
    private javax.swing.JLabel feet_label;
    private javax.swing.JTextField feetbox;
    private javax.swing.JLabel height_label;
    private javax.swing.JLabel inches_label;
    private javax.swing.JTextField inchesbox;
    private javax.swing.JSeparator lineone;
    private javax.swing.JSeparator linetwo;
    private javax.swing.JLabel normal_label;
    private javax.swing.JLabel obesity_label;
    private javax.swing.JLabel overweight_label;
    private javax.swing.JLayeredPane panel;
    private javax.swing.JLabel pounds_label;
    private javax.swing.JLabel underweight_label;
    private javax.swing.JLabel weight_label;
    private javax.swing.JTextField weightbox;
    // End of variables declaration//GEN-END:variables
}
