/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentquiz;

/**
 *
 * @author Gibby
 */
public class quizgui extends javax.swing.JFrame {

    private quiz quiz1;
    private int right;
    private int wrong;
    student s = new student();
    
    /**
     * Creates new form 
     */
    public quizgui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Startpage = new javax.swing.JPanel();
        Startbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idnum = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Quizpage = new javax.swing.JPanel();
        questionfield = new javax.swing.JLabel();
        checkbtn = new javax.swing.JButton();
        userin = new javax.swing.JTextField();
        correct = new javax.swing.JLabel();
        nextbtn = new javax.swing.JButton();
        feedback = new javax.swing.JLabel();
        Resultspage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        quizres = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new java.awt.CardLayout());

        Startpage.setBackground(new java.awt.Color(255, 255, 255));
        Startpage.setForeground(new java.awt.Color(0, 0, 0));

        Startbtn.setText("Start");
        Startbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartbtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("This program is a simple math quiz. There are 10 random questions");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("When Division is required please round to two decimal places");

        idnum.setText("Id Number");
        idnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idnumActionPerformed(evt);
            }
        });

        name.setText("Name");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Please remember to use commas for thousand values");

        javax.swing.GroupLayout StartpageLayout = new javax.swing.GroupLayout(Startpage);
        Startpage.setLayout(StartpageLayout);
        StartpageLayout.setHorizontalGroup(
            StartpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartpageLayout.createSequentialGroup()
                .addGroup(StartpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StartpageLayout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(Startbtn))
                    .addGroup(StartpageLayout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addGroup(StartpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idnum, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(name)))
                    .addGroup(StartpageLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel3))
                    .addGroup(StartpageLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartpageLayout.createSequentialGroup()
                .addGap(0, 63, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        StartpageLayout.setVerticalGroup(
            StartpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StartpageLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Startbtn)
                .addGap(63, 63, 63))
        );

        Background.add(Startpage, "card2");

        Quizpage.setBackground(new java.awt.Color(255, 255, 255));

        questionfield.setForeground(new java.awt.Color(0, 0, 0));
        questionfield.setText("This is where question will go");

        checkbtn.setText("Check");
        checkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkbtnActionPerformed(evt);
            }
        });

        userin.setText("Enter Here");
        userin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userinActionPerformed(evt);
            }
        });

        nextbtn.setText("Next");
        nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtnActionPerformed(evt);
            }
        });

        feedback.setForeground(new java.awt.Color(255, 51, 51));
        feedback.setText("Correct or incorrect goes here");

        javax.swing.GroupLayout QuizpageLayout = new javax.swing.GroupLayout(Quizpage);
        Quizpage.setLayout(QuizpageLayout);
        QuizpageLayout.setHorizontalGroup(
            QuizpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QuizpageLayout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(QuizpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizpageLayout.createSequentialGroup()
                        .addGroup(QuizpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(QuizpageLayout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(questionfield)
                                .addGap(18, 18, 18)
                                .addComponent(userin, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(QuizpageLayout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addGroup(QuizpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nextbtn)
                                    .addComponent(checkbtn))))
                        .addGap(26, 26, 26)
                        .addComponent(correct)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizpageLayout.createSequentialGroup()
                        .addComponent(feedback)
                        .addGap(165, 165, 165))))
        );
        QuizpageLayout.setVerticalGroup(
            QuizpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuizpageLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(feedback)
                .addGap(18, 18, 18)
                .addGroup(QuizpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(questionfield)
                    .addComponent(userin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(correct))
                .addGap(41, 41, 41)
                .addComponent(checkbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextbtn)
                .addGap(92, 92, 92))
        );

        Background.add(Quizpage, "card3");

        Resultspage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("You are now finished with the quiz. Your grade has been recorded in the grades.txt file");

        quizres.setForeground(new java.awt.Color(0, 0, 0));
        quizres.setText("This is where the results will go");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("This can be found in the project folder");

        javax.swing.GroupLayout ResultspageLayout = new javax.swing.GroupLayout(Resultspage);
        Resultspage.setLayout(ResultspageLayout);
        ResultspageLayout.setHorizontalGroup(
            ResultspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultspageLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(34, 34, 34))
            .addGroup(ResultspageLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(ResultspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(quizres, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ResultspageLayout.setVerticalGroup(
            ResultspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultspageLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(58, 58, 58)
                .addComponent(quizres)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        Background.add(Resultspage, "card4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartbtnActionPerformed
        // TODO add your handling code here:
        
        
        if(name.getText().equals("") == false && idnum.getText().equals("") == false && name.getText().equals("Name") == false && idnum.getText().matches("[0-9]*") == true)
        {
        Startpage.setVisible(false);
        Quizpage.setVisible(true);
        quiz1 = new quiz();
        questionfield.setText(quiz1.quest());
        nextbtn.setVisible(false);
        feedback.setVisible(false);
        userin.setText("");
        s.setname(name.getText());
        s.setid(idnum.getText());
        s.testing();
        }
        
        
    }//GEN-LAST:event_StartbtnActionPerformed

    private void checkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkbtnActionPerformed
        // TODO add your handling code here:
        checkbtn.setVisible(false);
       
      
        
        correct.setText(quiz1.Answer());
        correct.setVisible(true);
        if(correct.getText().equals(userin.getText()))
        {
            right = right + 1;
            feedback.setText("Correct!");
            feedback.setVisible(true);
        }
        else
        {
            wrong = wrong + 1;
            feedback.setText("Incorrect");
            feedback.setVisible(true);
               
        }
        
        System.out.println(right + " right");
        System.out.println(wrong + " wrong");
        nextbtn.setVisible(true);
        
    }//GEN-LAST:event_checkbtnActionPerformed

    private void userinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userinActionPerformed

    private void nextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbtnActionPerformed
         nextbtn.setVisible(false);
         correct.setVisible(false);
        if(right + wrong == 10)
        {
           Quizpage.setVisible(false);
           Resultspage.setVisible(true);
           double grade = Double.valueOf(right) / 10;
           grade = grade * 100;
           System.out.println(grade);
           quizres.setText(s.getname() + " got " + Double.toString(grade) + " points");
           s.setgrade(grade);
           s.write();
        }
        
        quiz1 = new quiz();
        questionfield.setText(quiz1.quest());
        userin.setText("");
        checkbtn.setVisible(true);
        feedback.setVisible(false);
        
    }//GEN-LAST:event_nextbtnActionPerformed

    private void idnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idnumActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quizgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quizgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quizgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quizgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quizgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Quizpage;
    private javax.swing.JPanel Resultspage;
    private javax.swing.JButton Startbtn;
    private javax.swing.JPanel Startpage;
    private javax.swing.JButton checkbtn;
    private javax.swing.JLabel correct;
    private javax.swing.JLabel feedback;
    private javax.swing.JTextField idnum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField name;
    private javax.swing.JButton nextbtn;
    private javax.swing.JLabel questionfield;
    private javax.swing.JLabel quizres;
    private javax.swing.JTextField userin;
    // End of variables declaration//GEN-END:variables
}
