/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guessing;

import guessing.card;
import guessing.deck;
import java.util.Random;

/**
 *
 * @author Gibby
 */
public class guessgui extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    deck gamedeck = new deck();
    int round = 0;
    int playerscore =0;
    int aiscore = 0;
    
    public guessgui() {
        initComponents();
        gamedeck.initializedeck(); 
        gamedeck.shuffle();
        //gamedeck.printallcards();
       //facedown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
        faceup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/b1fv.png")));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        facedown = new javax.swing.JLabel();
        faceup = new javax.swing.JLabel();
        Play = new javax.swing.JButton();
        Score = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Guess = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Guessing Game");

        Play.setText("Play");
        Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayActionPerformed(evt);
            }
        });

        Score.setForeground(new java.awt.Color(255, 255, 255));
        Score.setText("Player Score: ");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Computer Score:");

        Guess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ace", "2", "3", "4", "5", "6", "7", "8", "9", "Jack", "Queen", "King" }));
        Guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Score)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(facedown)
                        .addGap(143, 143, 143)
                        .addComponent(faceup))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Guess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Play))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(facedown)
                    .addComponent(faceup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(Guess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Play)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Score)
                    .addComponent(jLabel2))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void PlayActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        
       
        
        
        //Create the card that is being guessed
        card playcard = gamedeck.getTopCard();
        //The actual value of the card that will be compared
        int cardvalue = playcard.getvalue();
        
        //Set the picture
        faceup.setIcon(new javax.swing.ImageIcon(getClass().getResource(playcard.getImage())));
       
        //This creates the players comparison value
        int player_guess = Guess.getSelectedIndex() + 1;
        
        
        //This creates the a.i.'s comparison value
        Random r = new Random();
        int ai_guess = r.nextInt(13)+1;
        facedown.setText("Computer Guess: "+ ai_guess);
        
        
        int compplay = (Math.abs(player_guess - cardvalue));
        int compai = (Math.abs(ai_guess - cardvalue));
        
        if(compplay < compai) // player wins
        {
            playerscore++;
            jLabel1.setText("Player Wins");
        }
        if(compai < compplay)//ai wins
        {
            aiscore++;
             jLabel1.setText("Computer Wins");
        }
       if(compai == compplay)
       {
           jLabel1.setText("Tie");
       }
        
         Score.setText("Player Score: " + playerscore);
        jLabel2.setText("Computer Score: " + aiscore);  
        
        round++;
        System.out.println(round);
        if(round ==10)
        {
            System.out.println("GAME OVER");
            if(playerscore < aiscore)
            {
                jLabel1.setText("Computer Wins The Game");
                gamedeck.initializedeck(); 
                gamedeck.shuffle();
                 round = 0;
                 playerscore =0;
                 aiscore = 0;
            }
            else if(aiscore < playerscore)
            {
                jLabel1.setText("Player Wins The Game");
                gamedeck.initializedeck(); 
                gamedeck.shuffle();
                 round = 0;
                 playerscore =0;
                  aiscore = 0;
            }
            else
            {
                jLabel1.setText("Tie Game");
                gamedeck.initializedeck(); 
                gamedeck.shuffle();
                 round = 0;
                 playerscore =0;
                aiscore = 0;
            }
                
            
                
                
        }
         
        
        
    }                                    

    private void GuessActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
      
        
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guessgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guessgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guessgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guessgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guessgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JComboBox<String> Guess;
    private javax.swing.JButton Play;
    private javax.swing.JLabel Score;
    private javax.swing.JLabel facedown;
    private javax.swing.JLabel faceup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
