/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab3;

/**
 *
 * @author Gibby
 */
public class TempGui extends javax.swing.JFrame {

    /**
     * Creates new form TempGui
     */
    public TempGui() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JLayeredPane();
        Tempconverter_label = new javax.swing.JLabel();
        dropdown1 = new javax.swing.JComboBox<>();
        dropdown2 = new javax.swing.JComboBox<>();
        calculatebutton = new javax.swing.JButton();
        clearbutton = new javax.swing.JButton();
        userinfield = new javax.swing.JTextField();
        resultsfield = new javax.swing.JTextField();
        equalslabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        Tempconverter_label.setForeground(new java.awt.Color(0, 0, 0));
        Tempconverter_label.setText("Temperature Converter");

        dropdown1.setBackground(new java.awt.Color(204, 204, 255));
        dropdown1.setForeground(new java.awt.Color(0, 0, 0));
        dropdown1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Celsius" }));
        dropdown1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown1ActionPerformed(evt);
            }
        });

        dropdown2.setBackground(new java.awt.Color(204, 204, 255));
        dropdown2.setForeground(new java.awt.Color(0, 0, 0));
        dropdown2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fahrenheit", "Celsius" }));
        dropdown2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdown2ActionPerformed(evt);
            }
        });

        calculatebutton.setBackground(new java.awt.Color(204, 204, 255));
        calculatebutton.setForeground(new java.awt.Color(0, 0, 0));
        calculatebutton.setText("Calculate");
        calculatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebuttonActionPerformed(evt);
            }
        });

        clearbutton.setBackground(new java.awt.Color(204, 204, 255));
        clearbutton.setForeground(new java.awt.Color(0, 0, 0));
        clearbutton.setText("Clear");
        clearbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbuttonActionPerformed(evt);
            }
        });

        userinfield.setBackground(new java.awt.Color(255, 255, 255));
        userinfield.setForeground(new java.awt.Color(0, 0, 0));

        resultsfield.setBackground(new java.awt.Color(255, 255, 255));
        resultsfield.setForeground(new java.awt.Color(0, 0, 0));
        resultsfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsfieldActionPerformed(evt);
            }
        });

        equalslabel.setBackground(new java.awt.Color(255, 255, 255));
        equalslabel.setForeground(new java.awt.Color(0, 0, 0));
        equalslabel.setText("=");

        panel.setLayer(Tempconverter_label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(dropdown1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(dropdown2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(calculatebutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(clearbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(userinfield, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(resultsfield, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panel.setLayer(equalslabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(calculatebutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userinfield)
                    .addComponent(dropdown1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equalslabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dropdown2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultsfield, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(Tempconverter_label)
                .addGap(111, 111, 111))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Tempconverter_label)
                .addGap(47, 47, 47)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userinfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultsfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(equalslabel))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropdown1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dropdown2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculatebutton)
                    .addComponent(clearbutton))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropdown1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdown1ActionPerformed

    private void dropdown2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdown2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dropdown2ActionPerformed

    private void resultsfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultsfieldActionPerformed

    private void calculatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebuttonActionPerformed
        // WHEN THEY HIT THE CALCULATE BUTTON DO STUFF HERE
        
        String firstsign = (dropdown1.getSelectedItem().toString());
        String secondsign = (dropdown2.getSelectedItem().toString());
        String number = (userinfield.getText());
        double dub;
        
        //This Temp Converter should only accept numbers. not just a negative sign
        if(number.matches("\\-?[0-9]*\\.?[0-9]*") == true && number.equals(".") == false && number.equals("-") == false && number.equals("-.") == false && number.equals("") == false)
        {
            
            if(firstsign.equals(secondsign) == true)
            {
              resultsfield.setText(number);
            }
            //If Farenheit comes first then celsius
            if(firstsign.equals("Fahrenheit") == true && secondsign.equals("Celsius") == true)
            {
                dub = Double.parseDouble(number);
                tempconverter calc = new tempconverter(dub, firstsign);
                resultsfield.setText(calc.run());
            }
            //If celsius comes first then fahrenheit
            if(firstsign.equals("Celsius") == true && secondsign.equals("Fahrenheit") == true)
            {
                dub = Double.parseDouble(number);
                tempconverter calc = new tempconverter(dub, firstsign);
                resultsfield.setText(calc.run());
            }
            
            
            
            
            
            
        }
        
    }//GEN-LAST:event_calculatebuttonActionPerformed

    private void clearbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbuttonActionPerformed
        // This should clear both text fields
        resultsfield.setText("");
        userinfield.setText("");
    }//GEN-LAST:event_clearbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tempconverter_label;
    private javax.swing.JButton calculatebutton;
    private javax.swing.JButton clearbutton;
    private javax.swing.JComboBox<String> dropdown1;
    private javax.swing.JComboBox<String> dropdown2;
    private javax.swing.JLabel equalslabel;
    private javax.swing.JLayeredPane panel;
    private javax.swing.JTextField resultsfield;
    private javax.swing.JTextField userinfield;
    // End of variables declaration//GEN-END:variables
}
